version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=sammy
      - POSTGRES_PASSWORD=your_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:

# version: '3'

# services:
#   db-postgres-evento:
#     image: postgres:alpine
#     container_name: database
#     restart: always
#     ports: 
#       - "5432:5432"
#     environment:
#       - POSTGRES_USE=admin
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=database
#     volumes:
#       - pgdata:/data/postgres

# volumes:
#     pgdata:
#       driver: local